/* Auto-generated by FlexiHAL Simulator plugin manager */
#define ADD_MY_PLUGIN
#include "grbl/hal.h"

extern void settings_lock_init(void);
extern void atci_init(void);

void my_plugin_init(void)
{
    settings_lock_init();
    atci_init();
}
