/* Auto-generated by FlexiHAL Simulator plugin manager */
#define ADD_MY_PLUGIN
#include "grbl/hal.h"

extern void atci_init(void);
extern void tooltable_init(void);
extern void exclusion_zones_init(void);

#if ATC_ENABLE == 2
extern void atc_init(void);
#endif

void my_plugin_init(void)
{
    atci_init();
    tooltable_init();
    exclusion_zones_init();

#if ATC_ENABLE == 2
    atc_init();
#endif
}
